/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.netbeans;

import java.awt.*;
import java.io.*;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.*;

/**
 *
 * @author fufei
 */
public class CalendarMemoApp extends javax.swing.JFrame {
    ImageIcon icon = new ImageIcon(this.getClass().getResource("icon.png"));
    final String[] WEEK_DAY_NAME = { "SUN", "MON", "TUE", "WED", "THR", "FRI", "SAT" };
    JButton[][] dateButs = new JButton[6][7];
    CalendarManager cm = new CalendarManager();

    /**
     * Creates new form CalendarMemoApp
     */
    public CalendarMemoApp() {
        initComponents();
        
        Calendar today = Calendar.getInstance(); 
        //左上方标签显示
        todayLabel.setText(today.get(2) + 1 + "/" + today.get(5) + "/" + today.get(1));
        //日历上面标签显示
        dateLabel.setText("<html><table width=100><tr><th><font size=5>" + ((today.get(2) + 1 < 10) ? "&nbsp;" : "")
						+ (today.get(2) + 1) + " / " +  today.get(1) + "</th></tr></table></html>");
        //将dateLabel赋予CalendarManager，方便标签的改动
        cm.setDateLabel(dateLabel);
        //将pointLabel赋予CalendarManager，方便标签的改动
        cm.setPointLabel(pointLabel);
        //将memoArea赋予CalendarManager，方便文本区域的显示
        cm.setMemoArea(memoArea);
        //将fileInfoLabel赋予CalendarManager，方便右上角文件信息的显示
        cm.setFileInfoLabel(fileInfoLabel);

        //初始化当天日历数据
        cm.initToday(dateButs, memoArea);
        //备忘录的日期
        pointLabel.setText(cm.getCalMonth() + 1 + "/" + cm.getCalDayOfMon() + "/" + cm.getCalYear());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        todayBtn = new javax.swing.JButton();
        todayLabel = new javax.swing.JLabel();
        leftYearBtn = new javax.swing.JButton();
        leftMonthBtn = new javax.swing.JButton();
        rightYearBtn = new javax.swing.JButton();
        rightMonthBtn = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        calDetailPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        fileInfoLabel = new javax.swing.JLabel();
        memoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pointLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoArea = new javax.swing.JTextArea();
        saveBut = new javax.swing.JButton();
        delBut = new javax.swing.JButton();
        clearBut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MemoCalendar v1.0");
        setIconImage(icon.getImage());

        todayBtn.setText("Today");
        todayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayBtnActionPerformed(evt);
            }
        });

        todayLabel.setText("jLabel1");

        leftYearBtn.setText("<<");
        leftYearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftYearBtnActionPerformed(evt);
            }
        });

        leftMonthBtn.setText("<");
        leftMonthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftMonthBtnActionPerformed(evt);
            }
        });

        rightYearBtn.setText(">>");
        rightYearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightYearBtnActionPerformed(evt);
            }
        });

        rightMonthBtn.setText(">");
        rightMonthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightMonthBtnActionPerformed(evt);
            }
        });

        dateLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todayBtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(leftYearBtn)
                        .addGap(18, 18, 18)
                        .addComponent(leftMonthBtn)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rightMonthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rightYearBtn))
                    .addComponent(todayLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todayBtn)
                    .addComponent(todayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftYearBtn)
                    .addComponent(leftMonthBtn)
                    .addComponent(rightYearBtn)
                    .addComponent(rightMonthBtn)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout calDetailPanelLayout = new javax.swing.GroupLayout(calDetailPanel);
        calDetailPanel.setLayout(calDetailPanelLayout);
        calDetailPanelLayout.setHorizontalGroup(
            calDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        calDetailPanelLayout.setVerticalGroup(
            calDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(calDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JButton[] weekDaysName = new JButton[7];
        for (int i = 0; i < 7; ++i) {
            weekDaysName[i] = new JButton(WEEK_DAY_NAME[i]);
            weekDaysName[i].setBorderPainted(false);
            weekDaysName[i].setContentAreaFilled(false);
            weekDaysName[i].setForeground(Color.WHITE);
            if (i == 0)
            weekDaysName[i].setBackground(new Color(200, 50, 50));
            else if (i == 6)
            weekDaysName[i].setBackground(new Color(50, 100, 200));
            else
            weekDaysName[i].setBackground(new Color(150, 150, 150));
            weekDaysName[i].setOpaque(true);
            weekDaysName[i].setFocusPainted(false);
            this.calDetailPanel.add(weekDaysName[i]);
        }
        for (int i = 0; i < 6; ++i) {
            for (int j = 0; j < 7; ++j) {
                this.dateButs[i][j] = new JButton();
                this.dateButs[i][j].setBorderPainted(false);
                this.dateButs[i][j].setContentAreaFilled(false);
                this.dateButs[i][j].setBackground(Color.WHITE);
                this.dateButs[i][j].setOpaque(true);
                this.dateButs[i][j].addActionListener(new CalButtonAciton(this));
                this.calDetailPanel.add(this.dateButs[i][j]);
            }
        }
        calDetailPanel.setLayout(new GridLayout(0, 7, 2, 2));
        calDetailPanel.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));

        fileInfoLabel.setText("jLabel1");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        memoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        memoPanel.setToolTipText("");
        memoPanel.setName(""); // NOI18N

        jLabel1.setText("please key in your memo");

        pointLabel.setText("jLabel2");

        memoArea.setColumns(20);
        memoArea.setRows(5);
        jScrollPane1.setViewportView(memoArea);

        saveBut.setText("save");
        saveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButActionPerformed(evt);
            }
        });

        delBut.setText("delete");
        delBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButActionPerformed(evt);
            }
        });

        clearBut.setText("cacel");
        clearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memoPanelLayout = new javax.swing.GroupLayout(memoPanel);
        memoPanel.setLayout(memoPanelLayout);
        memoPanelLayout.setHorizontalGroup(
            memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoPanelLayout.createSequentialGroup()
                .addGroup(memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(memoPanelLayout.createSequentialGroup()
                                .addGroup(memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(memoPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(pointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(memoPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(saveBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(delBut)
                        .addGap(50, 50, 50)
                        .addComponent(clearBut)))
                .addContainerGap())
        );
        memoPanelLayout.setVerticalGroup(
            memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pointLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBut)
                    .addComponent(delBut)
                    .addComponent(clearBut))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        messageLabel.setText("hello,world");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayBtnActionPerformed
        cm.setToday(dateButs);
    }//GEN-LAST:event_todayBtnActionPerformed

    private void leftMonthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftMonthBtnActionPerformed
        cm.moveMonth(-1, dateButs);
    }//GEN-LAST:event_leftMonthBtnActionPerformed

    private void rightMonthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightMonthBtnActionPerformed
        cm.moveMonth(1, dateButs);
    }//GEN-LAST:event_rightMonthBtnActionPerformed

    private void leftYearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftYearBtnActionPerformed
        cm.moveMonth(-12, dateButs);
    }//GEN-LAST:event_leftYearBtnActionPerformed

    private void rightYearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightYearBtnActionPerformed
         cm.moveMonth(12, dateButs);
    }//GEN-LAST:event_rightYearBtnActionPerformed

    private void saveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButActionPerformed
        try {
                File f = new File("MemoData");
                if (!(f.isDirectory()))
                        f.mkdir();

                String memo = memoArea.getText();
                if (memo.length() > 0) {
                        BufferedWriter out = new BufferedWriter(new FileWriter("MemoData/" + cm.calYear
                                        + ((cm.calMonth + 1 < 10) ? "0" : "") + (cm.calMonth + 1)
                                        + ((cm.calDayOfMon < 10) ? "0" : "") + cm.calDayOfMon
                                        + ".txt"));
                        String str = memoArea.getText();
                        out.write(str);
                        out.close();
                        messageLabel.setText(cm.calYear
                                        + ((cm.calMonth + 1 < 10) ? "0" : "") + (cm.calMonth + 1)
                                        + ((cm.calDayOfMon < 10) ? "0" : "") + cm.calDayOfMon
                                        + ".txt" + " saved the memo.");
                        cm.showCal(dateButs);
                        return;
                }
                messageLabel.setText("NO memo Info! ");
        } catch (IOException e) {
                messageLabel.setText("<html><font color=red>ERROR : " + e.getMessage() + "</html>");
        }
    }//GEN-LAST:event_saveButActionPerformed

    private void delButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButActionPerformed
        memoArea.setText("");
        File f = new File("MemoData/" + cm.calYear
                        + ((cm.calMonth + 1 < 10) ? "0" : "") + (cm.calMonth + 1)
                        + ((cm.calDayOfMon < 10) ? "0" : "") + cm.calDayOfMon + ".txt");
        if (f.exists()) {
                f.delete();
                messageLabel.setText("deleted!");
        } else {
                messageLabel.setText("no memo exists!");
        }
        cm.showCal(dateButs);
    }//GEN-LAST:event_delButActionPerformed

    private void clearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButActionPerformed
        memoArea.setText(null);
	messageLabel.setText("cleared.");
    }//GEN-LAST:event_clearButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarMemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarMemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarMemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarMemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarMemoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calDetailPanel;
    private javax.swing.JButton clearBut;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delBut;
    private javax.swing.JLabel fileInfoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftMonthBtn;
    private javax.swing.JButton leftYearBtn;
    private javax.swing.JTextArea memoArea;
    private javax.swing.JPanel memoPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel pointLabel;
    private javax.swing.JButton rightMonthBtn;
    private javax.swing.JButton rightYearBtn;
    private javax.swing.JButton saveBut;
    private javax.swing.JButton todayBtn;
    private javax.swing.JLabel todayLabel;
    // End of variables declaration//GEN-END:variables
}
